class User < ApplicationRecord
  ROLES = %w[viewer admin].freeze
  # users.provider for accounts that sign in with a password. OIDC users have
  # openid_connect:<issuer> instead, and never a usable password.
  PASSWORD_PROVIDER = "password".freeze
  AUDIT_TYPE = "user".freeze
  MAX_PASSWORD_BYTES = ActiveModel::SecurePassword::MAX_PASSWORD_LENGTH_ALLOWED
  # Applies to every password set, whether generated by users:create and
  # users:reset_password or chosen by the user on the change password page.
  MIN_PASSWORD_LENGTH = 12
  REVOKE_SESSIONS_SQL = "UPDATE users SET session_generation = session_generation + 1 " \
                        "WHERE id = $1 RETURNING session_generation".freeze

  # OIDC users have no password, so the built-in validations, which demand
  # one, are off. Password users get the equivalent checks below.
  has_secure_password validations: false

  normalizes :email, with: ->(email) { email.strip.downcase }

  validates :email, presence: true
  validates :role, inclusion: { in: ROLES }
  validates :password, confirmation: true
  validate :password_usable

  # The user for a password login, or nil. Only active password users can
  # match. Every other case, unknown email included, still costs one bcrypt
  # hash (authenticate_by hashes against a throwaway record when nothing
  # matches), so response time doesn't reveal which emails exist.
  def self.authenticate_password_login(email:, password:)
    return nil unless email.is_a?(String) && password.is_a?(String)
    return nil if password.bytesize > MAX_PASSWORD_BYTES

    where(provider: PASSWORD_PROVIDER, active: true).authenticate_by(email: email, password: password)
  end

  def admin?
    role == "admin"
  end

  def password_login?
    provider == PASSWORD_PROVIDER
  end

  # Sets and saves a password the user chose, checked against the same
  # validations as any other password, plus a confirmation that must match.
  # Returns false, with errors, if it's refused. The caller checks the
  # current password first. A saved change ends all the user's sessions; the
  # caller restarts its own with the new session_generation.
  def change_password(new_password, confirmation)
    errors.clear
    errors.add(:base, "Only password users can change their password") unless password_login?
    errors.add(:password, :blank) unless new_password.is_a?(String) && new_password.present?
    errors.add(:password_confirmation, :blank) unless confirmation.is_a?(String) && confirmation.present?
    return false if errors.any?

    self.password = new_password
    self.password_confirmation = confirmation
    self.class.transaction do
      saved = save
      revoke_sessions! if saved
      saved
    end
  end

  # Ends every session this user has: each session stores the generation it
  # started with, and ApplicationController refuses one that's behind. The
  # bump is a single UPDATE, so concurrent bumps all count and a stale copy of
  # the row can't undo one. Returns the new generation, which is also set on
  # this object.
  def revoke_sessions!
    generation = self.class.lease_connection.select_value(REVOKE_SESSIONS_SQL, "User Revoke Sessions", [id])
    raise ActiveRecord::RecordNotFound.new("Couldn't find User with id #{id}", self.class.name, :id, id) if generation.nil?

    self[:session_generation] = Integer(generation)
    clear_attribute_change(:session_generation)
    session_generation
  end

  # An HMAC of the password digest, kept in the session at sign-in. A new
  # password means a new digest, so sessions started before the change stop
  # matching and are dropped. nil for users without a password (OIDC).
  # change_password and users:reset_password also bump session_generation;
  # this check stays as a backstop that needs no bump, so a password set any
  # other way (a console, a future code path) still ends old sessions.
  def credential_fingerprint
    return nil unless password_login? && password_digest.present?

    OpenSSL::HMAC.hexdigest("SHA256", self.class.credential_fingerprint_key, password_digest)
  end

  def self.credential_fingerprint_key
    Rails.application.key_generator.generate_key("rotten user credential fingerprint", 32)
  end

  private

  def password_usable
    errors.add(:password, :blank) if password_login? && password_digest.blank?
    errors.add(:password, :too_short, count: MIN_PASSWORD_LENGTH) if password && password.length < MIN_PASSWORD_LENGTH
    errors.add(:password, :too_long, count: MAX_PASSWORD_BYTES) if password && password.bytesize > MAX_PASSWORD_BYTES
  end
end
