package fingerprint

import (
	"bufio"
	"flag"
	"fmt"
	"io"
	"log"
	"os"
	"runtime/debug"
	"strings"
	"testing"
)

var updateGolden = flag.Bool("update", false, "regenerate testdata/fingerprints.golden")

const (
	corpusPath = "testdata/fingerprint_corpus.sql"
	goldenPath = "testdata/fingerprints.golden"
	casePrefix = "-- case: "
)

type corpusCase struct {
	name  string
	query string
}

// loadCorpus splits the corpus into cases. Full-line "--" comments that
// aren't case headers get ignored, including the file comment at the top.
func loadCorpus(t *testing.T) []corpusCase {
	t.Helper()
	f, err := os.Open(corpusPath)
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	return parseCorpus(t, f)
}

// parseCorpus does the splitting for loadCorpus.
func parseCorpus(t *testing.T, r io.Reader) []corpusCase {
	t.Helper()
	var cases []corpusCase
	var cur *corpusCase
	var lines []string
	flush := func() {
		if cur != nil {
			cur.query = strings.TrimSpace(strings.Join(lines, "\n"))
			cases = append(cases, *cur)
		}
	}
	seen := map[string]bool{}
	sc := bufio.NewScanner(r)
	for sc.Scan() {
		line := sc.Text()
		if name, ok := strings.CutPrefix(line, casePrefix); ok {
			flush()
			name = strings.TrimSpace(name)
			if seen[name] {
				t.Fatalf("duplicate case name %q", name)
			}
			seen[name] = true
			cur, lines = &corpusCase{name: name}, nil
			continue
		}
		// Full-line comments aren't part of any query. Comments inside a
		// query line stay, since marginalia cases rely on them.
		if strings.HasPrefix(strings.TrimSpace(line), "--") {
			continue
		}
		lines = append(lines, line)
	}
	if err := sc.Err(); err != nil {
		t.Fatal(err)
	}
	flush()
	if len(cases) == 0 {
		t.Fatal("corpus has no cases")
	}
	for _, c := range cases {
		if c.query == "" {
			t.Fatalf("case %q has no query", c.name)
		}
	}
	return cases
}

// pgQueryModule returns "path version" for the pg_query_go module linked into
// the test binary, with " => path version" appended when it's replaced.
func pgQueryModule(t *testing.T) string {
	t.Helper()
	info, ok := debug.ReadBuildInfo()
	if !ok {
		t.Fatal("no build info in test binary")
	}
	for _, dep := range info.Deps {
		if !strings.HasPrefix(dep.Path, "github.com/pganalyze/pg_query_go/") {
			continue
		}
		s := dep.Path + " " + dep.Version
		if r := dep.Replace; r != nil {
			s += " => " + strings.TrimSpace(r.Path+" "+r.Version)
		}
		return s
	}
	t.Fatal("pg_query_go not found in build info")
	return ""
}

func renderGolden(t *testing.T, cases []corpusCase) string {
	var b strings.Builder
	b.WriteString("# Generated by `make golden`. One line per corpus case: name, then fingerprint or error.\n")
	fmt.Fprintf(&b, "# %s\n", pgQueryModule(t))
	for _, c := range cases {
		fp, err := Normalized(c.query, Options{})
		if err != nil {
			fmt.Fprintf(&b, "%s\terror: %v\n", c.name, err)
		} else {
			fmt.Fprintf(&b, "%s\t%s\n", c.name, fp)
		}
	}
	return b.String()
}

// TestFingerprintGolden pins Normalized output so dependency
// upgrades can't silently regroup queries. It's pure: no database.
//
// Run `make golden` after any change to pg_query_go or the normalization code
// in fingerprint.go, then review `git diff internal/fingerprint/testdata/fingerprints.golden` to
// decide whether the changes are intended. Don't edit the golden file by
// hand. Error text is part of the golden output, so changed error messages
// show up in the diff too. The header records the pg_query_go version from
// the build info, so a bump that skips regenerating fails here. Without -update, any
// mismatch fails the test.
func TestFingerprintGolden(t *testing.T) {
	cases := loadCorpus(t)

	// Normalized logs every failure; keep test output readable.
	log.SetOutput(io.Discard)
	defer log.SetOutput(os.Stderr)

	got := renderGolden(t, cases)

	if *updateGolden {
		if err := os.WriteFile(goldenPath, []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("wrote %s", goldenPath)
		return
	}

	want, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("reading golden file (run `make golden` to create it): %v", err)
	}
	if got == string(want) {
		return
	}
	gotLines := strings.Split(got, "\n")
	wantLines := strings.Split(string(want), "\n")
	for i := 0; i < max(len(gotLines), len(wantLines)); i++ {
		var g, w string
		if i < len(gotLines) {
			g = gotLines[i]
		}
		if i < len(wantLines) {
			w = wantLines[i]
		}
		if g != w {
			t.Errorf("line %d:\n  got:  %s\n  want: %s", i+1, g, w)
		}
	}
	t.Error("fingerprints changed; if intended, regenerate with `make golden` and review the diff")
}
